ingredients_translated = {
    "Rosehips": "Hagebutten",
    "Sugar": "Zucker",
    "Lemon juice": "Zitronensaft",
    "Acidity regulator": "Säureregulator",
    "Flavor": "Aroma",
    "Tea extract": "Tee-Extrakt",
    "Vegetable oils": "pflanzliche Öle",
    "Table salt": "Speisesalz",
    "Paprika": "Paprika",
    "Natural flavor": "natürliches Aroma",
    "Onion": "Zwiebel",
    "Yeast extract": "Hefeextrakt",
    "Garlic": "Knoblauch",
    "Coloring": "Farbstoff",
    "Mineral water": "Mineralwasser",
    "Glucose": "Glukose",
    "Carbon dioxide": "Kohlensäure",
    "Taurine": "Taurin",
    "Caffeine": "Koffein",
    "Pantothenic acid": "Pantothensäure",
    "Flavors": "Aromen",
    "Flavor enhancer": "Geschmacksverstärker",
    "Preservatives": "Konservierungsstoffe",
    "Sweeteners": "Süßungsmittel",
    "Aspartame": "Aspartam",
    "Wheat flour": "Weizenmehl",
    "Glucose-fructose syrup": "Glukose-Fruktosesirup",
    "Cocoa butter": "Kakaobutter",
    "Whole milk powder": "Vollmilchpulver",
    "Sweet whey powder": "Süßmolkenpulver",
    "Cocoa mass": "Kakaomasse",
    "Caramel sugar syrup": "Karamellzuckersirup",
    "Spices": "Gewürze",
    "Cinnamon": "Zimt",
    "Sunflower oil": "Sonnenblumenöl",
    "Skimmed milk powder": "Magermilchpulver",
    "Emulsifier": "Emulgator",
    "Salt": "Salz",
    "Butterfat": "Butterreinfett",
    "Glucose syrup": "Glukosesirup",
    "Dextrose": "Dextrose",
    "Gelatin": "Gelatine",
    "Fruit and plant concentrates": "Frucht- und Pflanzenkonzentrate",
    "Lemon": "Zitrone"
}